version: '3.9'

services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: ./jenkins
      args:
        DOCKER_VERSION: 20.10.8
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Xmx2048m"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data: