version: '3.9'

services:
  jenkins:
    container_name: jenkins
    hostname: jenkins
    build:
      context: ./jenkins
      args:
        DOCKER_VERSION: 20.10.8
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins-data:/var/jenkins_home:rw

volumes:
  jenkins-data:
